--local autocmd = vim.api.nvim_create_autocmd

-- rather do this in fileptye.lua
-- autocmd(
--   { "FileType" },
--   {
--     pattern = "json",
--     callback = function() 
--       vim.cmd "set ft=jsonc syntax=jsonc"
--     end
--   }
-- )
